"""add topic & language columns

Revision ID: 944539d078f2
Revises: 13ab4375aecf
Create Date: 2025-11-10 16:53:20.719901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944539d078f2'
down_revision: Union[str, Sequence[str], None] = '13ab4375aecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
     # Создаем Enum в БД
    flashcard_status = sa.Enum('NEW', 'INPROGRESS', 'DONE', name='flashcardstatus')
    flashcard_status.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('flashcards', sa.Column('language', sa.String(), nullable=True))
     # Меняем тип с кастом
    op.alter_column(
        'flashcards',
        'status',
        type_=flashcard_status,
        existing_type=sa.VARCHAR(),
        postgresql_using="status::flashcardstatus"
    )
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('flashcards', 'status',
               existing_type=sa.Enum('NEW', 'INPROGRESS', 'DONE', name='flashcardstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('flashcards', 'language')
    op.drop_column('flashcards', 'topic')
    # ### end Alembic commands ###
