"""add fields to languages

Revision ID: acde8fe8dfc0
Revises: 944539d078f2
Create Date: 2025-11-11 14:17:06.733702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acde8fe8dfc0'
down_revision: Union[str, Sequence[str], None] = '944539d078f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('language_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'flashcards', 'languages', ['language_id'], ['id'])
    op.drop_column('flashcards', 'language')
    op.add_column('languages', sa.Column('code', sa.String(), nullable=False))
    op.drop_constraint(op.f('languages_name_key'), 'languages', type_='unique')
    op.create_unique_constraint(None, 'languages', ['code'])
    op.drop_column('languages', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('languages', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'languages', type_='unique')
    op.create_unique_constraint(op.f('languages_name_key'), 'languages', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('languages', 'code')
    op.add_column('flashcards', sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'flashcards', type_='foreignkey')
    op.drop_column('flashcards', 'language_id')
    # ### end Alembic commands ###
